language: python

python:
    - "2.7"
    - "3.4"

install:
    - pip install -r requirements.txt
    - pip install -rtests/requirements.txt
    - pip install nose

script: nosetests --with-coverage

after_success:
    - pip install coveralls
    - coveralls
