language: python

python:
    - "2.7"

install:
    - pip install -r requirements.txt
    - pip install -rtests/requirements.txt
    - pip install nose

script: python setup.py nosetests --with-coverage --cover-package=docker_registry.drivers.ufile

after_success:
    - pip install coveralls
    - coveralls
