language: python

python:
    - "2.7"
    - "3.4"

virtualenv:
    system_site_packages: true

install:
    - pip install -r requirements.txt
    - pip install -rtests/requirements.txt
    - pip install nose

script: python setup.py nosetests

after_success:
    - pip install coveralls
    - coveralls
